diplom_project/internet_shop/account/urls.py
import django
from django.urls import re_path
from . import views


app_name = 'account'

urlpatterns = [
    re_path(r'login/', views.user_login, name='login'),
    re_path(r'logout/', views.logout_user, name='logout'),
    re_path(r'register/', views.register, name='register'),
    re_path(r'invalid_login/', views.invalid_login, name='invalid_login'),

]

diplom_project/internet_shop/cart/urls.py
from django.urls import re_path
from . import views

app_name = 'cart'

urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

diplom_project/internet_shop/internet_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('modakids/', include('shop.urls')),
    path('modakids/cart/', include('cart.urls')),
    path('modakids/orders/', include('orders.urls')),
    path('modakids/account/', include('account.urls')),
    path('modakids/stock/', include('stock.urls'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diplom_project/internet_shop/cart/models.py
from django.db import models

# Create your models here.

diplom_project/internet_shop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label='Количество')
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

diplom_project/internet_shop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'detail.html', {'cart': cart})

diplom_project/internet_shop/cart/templates/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/cart.css' %}" type="text/css">
    <title>Корзина</title>
</head>
<body>
    <div class="first">
        <div class="telephone">
            <div id="tel_logo">
                <img src="{% static 'img/main/smartphone.png' %}" height="25px" width="25px"  alt="photo">
            </div>
            <div id="number">
                <a href="tel:+375(29)396-76-42">+375(29)396-76-42</a>
            </div>
        </div>
        <div id="autorization">
            {%  if request.user.is_authenticated %}
                <p id="class"> {{ user.username }} | <a href="{% url "account:logout" %}">Выйти</a></p>
            {% else %}
                <p id="class"><a href="{% url "account:login" %}">Вход</a> | <a href="{% url "account:register" %}">Регистрация</a></p>
            {% endif %}
        </div>
    </div>
    <!---->
    <div class="content">
        <div class="navigation">
            <div id="mainlogo">
                <img src="{% static "/img/main/modakids-logo.gif" %}" height="150px" width="300px" alt="photo">
            </div>
            <div class="menu">
                <ul class="full-width">
                    <li><a href="{% url 'main' %}">ГЛАВНАЯ</a></li>
                    <li><a href="{% url 'catalog' %}">КАТАЛОГ</a></li>
                    <li><a href="{% url 'delivery' %}">ИНФОРМАЦИЯ</a>
                    <li><a href="{% url 'stock_catalog' %}">АКЦИИ</a></li>
                    <li><a href="{% url 'about' %}">О НАС</a></li>
                </ul>
            </div>
            <div class="container">
                <form action="{% url "cart:cart_detail" %}" style="margin: 10px" id="form-btn">
                    <button id="cart_btn" style="width: 70px; height: 70px;">
                    </button>
                </form>
                <div class="cart">
                    {% with total_items=cart|length %}
                        {% if cart|length > 0 %}
                            <a href="{% url "cart:cart_detail" %}">
                            <div id="sum" style="border: 1px black solid; padding: 5px">
                                {{ total_items }} <br>
                                {{ cart.get_total_price }} руб.
                            </div>
                            </a>
                        {% else %}
                            Корзина пуста
                        {% endif %}
                    {% endwith %}
                </div>
            </div>
        </div>
            <!---->
        <div class="mainview">
            <div id="title">
                <h1>Товары для детей от <span>"0+"</span></h1>
            </div>
            <div id="mainphoto">
                <img src="{% static 'img/main/main photo.jpeg' %}" width="100%" height="100%">
            </div>
        </div>
        <div id="cart_menu">
            <h2 id="cart_name">Ваша корзина</h2>
            <table id="cart">
                <thead id="table-name">
                    <tr>
                        <th>Картинка</th>
                        <th>Товар</th>
                        <th>Количество</th>
                        <th>Цена</th>
                        <th>Стомость</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in cart %}
                        {% with product=item.product %}
                            <tr>
                                <td>
                                    <a href="{{ product.get_absolute_url }}">
                                        <img src="
                                            {% if product.image %}
                                                {{ product.image.url }}
                                            {% else %}
                                                {% static "img/no_image.png" %}
                                            {% endif %}" id="cart-photo">
                                    </a>
                                </td>
                                <td>{{ product.name }}</td>
                                <td>{{ item.quantity }}</td>
                                <td class="num">${{ item.price }}</td>
                                <td class="num">${{ item.total_price }}</td>
                                <td><a href="{% url "cart:cart_remove" product.id %}">Удалить</a></td>
                            </tr>
                        {% endwith %}
                    {% endfor %}
                </tbody>
            </table>
            <div class="empty_card">
                {% with total_items=cart|length %}
                    {% if cart|length < 1 %}
                        <p id="empty-cart-text">Ваша корзина пуста</p>
                        <img src={% static "img/empty-cart.jpeg" %}>
                    {% endif %}
                {% endwith %}
            </div>
            <div id="total">
                <h3 style="font-size: 20px" id="total-text">Итого: {{ cart.get_total_price }} $</h3>
                <div class="main-btn">
                    <div id="btn">
                        <a href="{% url "catalog" %}" id="button_light">Продолжить покупки</a>
                    </div>
                    <div id="btn">
                        <a href="{% url "order_create" %}" id="button-cart">Оформить заказ</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="futer">
        <div id="end-block">
            <h2 style="text-align: left; font-size: 22px;">Следуй за нами:</h2>
            <a href="https://www.instagram.com/evgenij_sidorovich/" target="_blank"><img src="{% static '/img/main/instagram.png' %}" width="40"
            height="40" alt=" Инстаграм"></a>
            <a href="https://vk.com/evgenij_sidorovich" target="_blank"><img src="{% static '/img/main/vk.png' %}" width="40"
            height="40" alt="ВК"></a>
        </div>
        <div id="end-block">
            <h2 style="text-align: left; font-size: 22px;">Время работы</h2>
            <p3>пн-пт: 9:00 - 20:00</p3><br>
            <p3>сб, вс: 9:00 - 19:00</p3><br>
        </div>
        <div id="end-block">
            <h2 style="text-align: left; font-size: 22px;"> Круглосуточная <br> поддержка</h2>
            <p3>+375(29)861-87-65</p3><br>
            <p3>support@gmail.com</p3>
        </div>
    </div>
</body>