diplom_project/internet_shop/account/urls.py
import django
from django.urls import re_path
from . import views


app_name = 'account'

urlpatterns = [
    re_path(r'login/', views.user_login, name='login'),
    re_path(r'logout/', views.logout_user, name='logout'),
    re_path(r'register/', views.register, name='register'),
    re_path(r'invalid_login/', views.invalid_login, name='invalid_login'),

]

diplom_project/internet_shop/cart/urls.py
from django.urls import re_path
from . import views

app_name = 'cart'

urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

diplom_project/internet_shop/internet_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('modakids/', include('shop.urls')),
    path('modakids/cart/', include('cart.urls')),
    path('modakids/orders/', include('orders.urls')),
    path('modakids/account/', include('account.urls')),
    path('modakids/stock/', include('stock.urls'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diplom_project/internet_shop/shop/urls.py
from django.urls import re_path
from . import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    re_path('^$', views.main, name='main'),
    re_path('about/', views.about, name='about'),
    path('information/', include([
        re_path('delivery/', views.delivery, name='delivery'),
        re_path('payment/', views.payment, name='payment'),
        re_path('return/', views.contact_view, name='return'),
        re_path('contacts/', views.contacts, name='contacts'),
        re_path('thanks/', views.thanks, name='thanks')
    ])),
    path('category/', include([
        re_path('^$', views.catalog, name='catalog'),
        re_path('(?P<id>\d+)/(?P<slug>[-\w]+)/', views.product_detail, name='product_detail'),
        re_path('(?P<category_slug>[-\w]+)/', views.product_list, name='product_list_by_category'),
    ])),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diplom_project/internet_shop/shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=50, db_index=True)
    slug = models.SlugField(max_length=50, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_list_by_category',
                        args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_detail',
                       args=[self.id, self.slug])


class Contact(models.Model):
    name = models.CharField(max_length=50)
    telephone = models.CharField(max_length=50)
    subject = models.CharField(max_length=50)
    message = models.CharField(max_length=100)

    def __str__(self):
        return self.subject

#
# class Comment(models.Model):
#     user = models.CharField(max_length=80)
#     body = models.TextField()
#     created = models.DateTimeField(auto_now_add=True)
#     active = models.BooleanField(default=True)
#
#     class Meta:
#         ordering = ('created',)
#
#     def __str__(self):
#         return self.body

diplom_project/internet_shop/shop/forms.py
from django import forms
from django.forms import Textarea, TextInput
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'telephone', 'subject', 'message']
        labels = {
            'name': 'Имя',
            'telephone': 'Телефон',
            'subject': 'Тема сообщения',
            'message': 'Сообщение'}
        widgets = {
            'message': Textarea(attrs={
                'placeholder': 'Напишите ваше сообщение'}),
            'name': TextInput(attrs={
                    'placeholder': 'Введите имя...'}),
            'telephone': TextInput(attrs={
                'placeholder': 'Введите телефон...'}),
            'subject': TextInput(attrs={
                'placeholder': 'Введите тему...'})
        }

#
# class CommentForm(forms.ModelForm):
#     class Meta:
#         model = Comment
#         fields = ('user', 'created', 'body')

diplom_project/internet_shop/shop/views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.views.generic import ListView

from .forms import ContactForm
from .models import Category, Product
from cart.forms import CartAddProductForm


def main(request):
    return render(request, "main.html")


def about(request):
    return render(request, "about.html")


def delivery(request):
    return render(request, "delivery.html")


def payment(request):
    return render(request, "payment.html")


# def return_things(request):
#     return render(request, "return.html")


def contacts(request):
    return render(request, "contacts.html")


def catalog(request):
    category = None
    categories = Category.objects.all()
    products = Product.objects.all()

    paginator = Paginator(products, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    cart_product_form = CartAddProductForm()

    return render(request,
                  'catalog.html',
                  {'category': category,
                   'categories': categories,
                   'products': products,
                   'page_obj': page_obj,
                   'cart_product_form': cart_product_form})


def product_list(request, category_slug=None):
    categories = Category.objects.all()
    category = get_object_or_404(Category, slug=category_slug)

    products = Product.objects.filter(category=category)
    paginator = Paginator(products, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    cart_product_form = CartAddProductForm()
    return render(request,
                  'category/all_products.html',
                  {'category': category,
                   'categories': categories,
                   'products': products,
                   'page_obj': page_obj,
                   'cart_product_form': cart_product_form})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'category/details.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})


def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)

        # Если форма заполнена корректно, сохраняем все введённые пользователем значения
        if form.is_valid():
            form_data = form.cleaned_data
            form.save()
            # Переходим на другую страницу, если сообщение отправлено
            return HttpResponseRedirect('/modakids/information/thanks/')
    else:
        # Заполняем форму
        form = ContactForm()
    # Отправляем форму на страницу
    return render(request, 'return.html', {'form': form})


def thanks(request):
    return render(request, 'thanks.html')


# def post_detail(request):
#
#     if request.method == 'POST':
#         comment_form = Comment(data=request.POST)
#         if comment_form.is_valid():
#             new_comment = comment_form.save(commit=False)
#             new_comment.save()
#     else:
#         comment_form = Comment()
#     return render(request,
#                   'detail.html',
#                  {'comment_form': comment_form})

diplom_project/internet_shop/shop/templates/about.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/about.css' %}" type="text/css">
    <title>О нас</title>
</head>
<body>
    <div class="first">
        <div class="telephone">
            <div id="tel_logo">
                <img src="{% static 'img/main/smartphone.png' %}" height="25px" width="25px"  alt="photo">
            </div>
            <div id="number">
                <a href="tel:+375(29)396-76-42">+375(29)396-76-42</a>
            </div>
        </div>
        <div id="autorization">
            {%  if request.user.is_authenticated %}
                <p id="class"> {{ user.username }} | <a href="{% url "account:logout" %}">Выйти</a></p>
            {% else %}
                <p id="class"><a href="{% url "account:login" %}">Вход</a> | <a href="{% url "account:register" %}">Регистрация</a></p>
            {% endif %}
        </div>
    </div>
    <!---->
    <div class="content">
        <div class="navigation">
            <div id="mainlogo">
                <img src="{% static "/img/main/modakids-logo.gif" %}" height="150px" width="300px" alt="photo">
            </div>
            <div class="menu">
                <ul class="full-width">
                    <li><a href="{% url 'main' %}">ГЛАВНАЯ</a></li>
                    <li><a href="{% url 'catalog' %}">КАТАЛОГ</a></li>
                    <li><a href="{% url 'delivery' %}">ИНФОРМАЦИЯ</a>
                    <li><a href="{% url 'stock_catalog' %}">АКЦИИ</a></li>
                    <li><a href="{% url 'about' %}">О НАС</a></li>
                </ul>
            </div>
            <div class="container">
                <form action="{% url "cart:cart_detail" %}" style="margin: 10px" id="form-btn">
                    <button id="cart_btn" style="width: 70px; height: 70px;">
                    </button>
                </form>
                <div class="cart">
                    {% with total_items=cart|length %}
                        {% if cart|length > 0 %}
                            <a href="{% url "cart:cart_detail" %}">
                            <div id="sum" style="border: 1px black solid; padding: 5px">
                                {{ total_items }} <br>
                                {{ cart.get_total_price }} руб.
                            </div>
                            </a>
                        {% else %}
                            Корзина пуста
                        {% endif %}
                    {% endwith %}
                </div>
            </div>
        </div>
        <!---->
        <div class="mainview">
            <div id="title">
                <h1>Товары для детей от <span>"0+"</span></h1>
            </div>
            <div id="mainphoto">
                <img src="{% static 'img/main/main photo.jpeg' %}" width="100%" height="100%">
            </div>
        </div>
        <div class='container-info'>
            <div id="about-us">
                <h2> О МАГАЗИНЕ</h2>
                <p>
                    Компания ""ModaKids является официальным поставщиком на белорусском  рынке товаров для детей.  Великолепный выбор всего необходимого для вашего ребёнка: коляски, стулья для кормления, пластиковые и деревянные комоды, детские автокресла, комплекты для новорожденных, комплекты на выписку, манежи, детские кроватки, кровати-трансформеры, наборы детской мебели, домики с шарами, велосипеды, самокаты, развивающие игрушки и т.д.<br>
                </p>
                <p>
                    Мы готовы радовать вас разнообразными товарами в области детской индустрии и представляем на рынке огромный ассортимент известных брэндов, таких как «Peg-Perego» /Италия/, «NANIA» /Франция/,«TUTIS» /Литва/, «KHW» /Германия/.<br>
                </p>
                <p>
                    В нашем интернет-магазине вы сможете приобрести оригинальные, качественные и сертифицированные товары, которые поставляет компания "ModaKids" в РБ. Мы очень надеемся, что вложенные в этот проект труд и знания помогут вам быстро, комфортно, удобно выбрать и приобрести всё, что нужно для вашего малыша. А профессиональные консультанты нашей компании готовы в любое время ответить на все вопросы.<br>
                </p>
                <p>
                    Добро пожаловать в интернет-магазин компании "ModaKids" !!!
                </p>
                <img id="missia" src="{% static 'img/about/missiya.png' %}" width="100%">
            </div>
        </div>
        <!---->
    </div>
        <!---->
    <div class="futer">
        <div id="end-block">
            <h2 style="text-align: left; font-size: 22px;">Следуй за нами:</h2>
            <a href="https://www.instagram.com/evgenij_sidorovich/" target="_blank"><img src="{% static '/img/main/instagram.png' %}" width="40"
            height="40" alt=" Инстаграм"></a>
            <a href="https://vk.com/evgenij_sidorovich" target="_blank"><img src="{% static '/img/main/vk.png' %}" width="40"
            height="40" alt="ВК"></a>
        </div>
        <div id="end-block">
            <h2 style="text-align: left; font-size: 22px;">Время работы</h2>
            <p3>пн-пт: 9:00 - 20:00</p3><br>
            <p3>сб, вс: 9:00 - 19:00</p3><br>
        </div>
        <div id="end-block">
            <h2 style="text-align: left; font-size: 22px;"> Круглосуточная <br> поддержка</h2>
            <p3>+375(29)861-87-65</p3><br>
            <p3>support@gmail.com</p3>
        </div>
    </div>
</body>
</html>

diplom_project/internet_shop/shop/templates/catalog.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/catalog.css' %}" type="text/css">
    <title>Каталог</title>
</head>
<body>
    <div class="first">
        <div class="telephone">
            <div id="tel_logo">
                <img src="{% static 'img/main/smartphone.png' %}" height="25px" width="25px"  alt="photo">
            </div>
            <div id="number">
                <a href="tel:+375(29)396-76-42">+375(29)396-76-42</a>
            </div>
        </div>
        <div id="autorization">
            {%  if request.user.is_authenticated %}
                <p id="class"> {{ user.username }} | <a href="{% url "account:logout" %}">Выйти</a></p>
            {% else %}
                <p id="class"><a href="{% url "account:login" %}">Вход</a> | <a href="{% url "account:register" %}">Регистрация</a></p>
            {% endif %}
        </div>
    </div>
    <!---->
    <div class="content">
        <div class="navigation">
            <div id="mainlogo">
                <img src="{% static "/img/main/modakids-logo.gif" %}" height="150px" width="300px" alt="photo">
            </div>
            <div class="menu">
                <ul class="full-width">
                    <li><a href="{% url 'main' %}">ГЛАВНАЯ</a></li>
                    <li><a href="{% url 'catalog' %}">КАТАЛОГ</a></li>
                    <li><a href="{% url 'delivery' %}">ИНФОРМАЦИЯ</a>
                    <li><a href="{% url 'stock_catalog' %}">АКЦИИ</a></li>
                    <li><a href="{% url 'about' %}">О НАС</a></li>
                </ul>
            </div>
            <div class="container">
                <form action="{% url "cart:cart_detail" %}" style="margin: 10px" id="form-btn">
                    <button id="cart_btn" style="width: 70px; height: 70px;">
                    </button>
                </form>
                <div class="cart">
                    {% with total_items=cart|length %}
                        {% if cart|length > 0 %}
                            <a href="{% url "cart:cart_detail" %}">
                            <div id="sum" style="border: 1px black solid; padding: 5px">
                                {{ total_items }} <br>
                                {{ cart.get_total_price }} руб.
                            </div>
                            </a>
                        {% else %}
                            Корзина пуста
                        {% endif %}
                    {% endwith %}
                </div>
            </div>
        </div>
        <!---->
        <div class="mainview">
            <div id="title">
                <h1>Товары для детей от <span>"0+"</span></h1>
            </div>
            <div id="mainphoto">
                <img src="{% static 'img/main/main photo.jpeg' %}" width="100%" height="100%" alt="photo">
            </div>
        </div>
        <div class='conteiner-info'>
            <div id="sidebar">
                <ul>
                    {% for c in categories %}
                        <button id="category_btn" style="background: #c462a0">
                            <a href="{{ c.get_absolute_url }}" style="color: #d1f4f6">{{ c.name }}</a>
                        </button>
                    {% endfor %}
                </ul>
            </div>
            <div id="all_products">
                {% for product in page_obj %}
                    <div class="product-item">
                        <img src="{{ product.image.url }}" style="width: 100%; height: 50%;" alt="No photo">
                        <div class="product-list">
                            <a href="{{ product.get_absolute_url }}" id="item-name">{{ product.name }}</a><br>
                            <span class="price">{{ product.price }}</span><br>
                                <form action="{% url "cart:cart_add" product.id %}" method="post">
                                    {{ cart_product_form }}
                                    {% csrf_token %}
                                    <input type="submit" value="Добавить в корзину" id="add-cart">
                                </form>
                        </div>
                    </div>
                {% endfor %}
                <div class="pagination">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a class="pagination_link" href="?page=1">&laquo;&laquo;</a>
                        {% endif %}
                        {% for num in page_obj.paginator.page_range %}
                        {% if num < page_obj.number and num < 4 %}
                            <a class="pagination_link" href="?page={{ num }}">{{ num }}</a>
                        {% elif num < page_obj.number and num > page_obj.number|add:-4 %}
                            <a class="pagination_link" href="?page={{ num }}">{{ num }}</a>
                        {% elif num == page_obj.number %}
                            <span class="pagination_link_pagination_link__active">{{ num }}</span>
                        {% elif num > page_obj.number and num < page_obj.number|add:4 %}
                            <a class="pagination_link" href="?page={{ num }}">{{ num }}</a>
                        {% elif num > page_obj.number and num > page_obj.paginator.num_pages|add:-3 %}
                            <a class="pagination_link" href="?page={{ num }}">{{ num }}</a>
                        {% endif %}
                    {% endfor %}
                        {% if page_obj.has_next %}
                            <a class="pagination_link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;&raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>
    </div>
        <!---->
    <div class="futer">
        <div id="end-block">
            <h2 style="text-align: left; font-size: 22px;">Следуй за нами:</h2>
            <a href="https://www.instagram.com/evgenij_sidorovich/" target="_blank"><img src="{% static '/img/main/instagram.png' %}" width="40"
            height="40" alt=" Инстаграм"></a>
            <a href="https://vk.com/evgenij_sidorovich" target="_blank"><img src="{% static '/img/main/vk.png' %}" width="40"
            height="40" alt="ВК"></a>
        </div>
        <div id="end-block">
            <h2 style="text-align: left; font-size: 22px;">Время работы</h2>
            <p3>пн-пт: 9:00 - 20:00</p3><br>
            <p3>сб, вс: 9:00 - 19:00</p3><br>
        </div>
        <div id="end-block">
            <h2 style="text-align: left; font-size: 22px;"> Круглосуточная <br> поддержка</h2>
            <p3>+375(29)861-87-65</p3><br>
            <p3>support@gmail.com</p3>
        </div>
    </div>
</body>
</html></title>
</head>
<body>

</body>
</html>

diplom_project/internet_shop/shop/templates/contacts.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/contacts.css' %}" type="text/css">
    <title>Контакты</title>
</head>
<body>
    <div class="first">
        <div class="telephone">
            <div id="tel_logo">
                <img src="{% static 'img/main/smartphone.png' %}" height="25px" width="25px"  alt="photo">
            </div>
            <div id="number">
                <a href="tel:+375(29)396-76-42">+375(29)396-76-42</a>
            </div>
        </div>
        <div id="autorization">
            {%  if request.user.is_authenticated %}
                <p id="class"> {{ user.username }} | <a href="{% url "account:logout" %}">Выйти</a></p>
            {% else %}
                <p id="class"><a href="{% url "account:login" %}">Вход</a> | <a href="{% url "account:register" %}">Регистрация</a></p>
            {% endif %}
        </div>
    </div>
    <!---->
    <div class="content">
        <div class="navigation">
            <div id="mainlogo">
                <img src="{% static "/img/main/modakids-logo.gif" %}" height="150px" width="300px" alt="photo">
            </div>
            <div class="menu">
                <ul class="full-width">
                    <li><a href="{% url 'main' %}">ГЛАВНАЯ</a></li>
                    <li><a href="{% url 'catalog' %}">КАТАЛОГ</a></li>
                    <li><a href="{% url 'delivery' %}">ИНФОРМАЦИЯ</a>
                    <li><a href="{% url 'stock_catalog' %}">АКЦИИ</a></li>
                    <li><a href="{% url 'about' %}">О НАС</a></li>
                </ul>
            </div>
            <div class="container">
                <form action="{% url "cart:cart_detail" %}" style="margin: 10px" id="form-btn">
                    <button id="cart_btn" style="width: 70px; height: 70px;">
                    </button>
                </form>
                <div class="cart">
                    {% with total_items=cart|length %}
                        {% if cart|length > 0 %}
                            <a href="{% url "cart:cart_detail" %}">
                            <div id="sum" style="border: 1px black solid; padding: 5px">
                                {{ total_items }} <br>
                                {{ cart.get_total_price }} руб.
                            </div>
                            </a>
                        {% else %}
                            Корзина пуста
                        {% endif %}
                    {% endwith %}
                </div>
            </div>
        </div>
        <!---->
        <div class="mainview">
            <div id="title">
                <h1>Товары для детей от <span>"0+"</span></h1>
            </div>
            <div id="mainphoto">
                <img src="{% static 'img/main/main photo.jpeg' %}" width="100%" height="100%">
            </div>
        </div>
        <div class='conteiner-info'>
            <div id='menu-block'>
                <ul id="block">
                    <li><a href="{% url 'delivery' %}">ДОСТАВКА</a></li>
                    <li><a href="{% url 'payment' %}">ОПЛАТА</a></li>
                    <li><a href="{%  url 'return' %}">ЗАМЕНА И ВОЗВРАТ ТОВАРА</a></li>
                    <li><a href="{% url 'contacts' %}">КОНТАКТЫ</a></li>
                </ul>
            </div>
            <div id="info-block" style="margin-left: 30px">
                <h2 >
                    Контакты
                </h2>
                <h3> Контактные телефоны:</h3>
                <p id="cont">+375(29)396-76-42</p>
                <p id="cont">+375(29)861-87-65</p>
                <p id="cont">E-mail: modakids@hmail.com</p>
                <p id="cont">Viber +375(29)3967642</p>
                <h3> Режим работы</h3>
                <p id="cont">Пн-Вс 9:00 - 19:00</p>
                <p id="cont" style="margin-top: 40px"> Прием заказов через интернет - <span style="color: red"> круглосуточно!</span> </p>
            </div>
        </div>
        <!---->
    </div>
        <!---->
    <div class="futer">
        <div id="end-block">
            <h2 style="text-align: left; font-size: 22px;">Следуй за нами:</h2>
            <a href="https://www.instagram.com/evgenij_sidorovich/" target="_blank"><img src="{% static '/img/main/instagram.png' %}" width="40"
            height="40" alt=" Инстаграм"></a>
            <a href="https://vk.com/evgenij_sidorovich" target="_blank"><img src="{% static '/img/main/vk.png' %}" width="40"
            height="40" alt="ВК"></a>
        </div>
        <div id="end-block">
            <h2 style="text-align: left; font-size: 22px;">Время работы</h2>
            <p3>пн-пт: 9:00 - 20:00</p3><br>
            <p3>сб, вс: 9:00 - 19:00</p3><br>
        </div>
        <div id="end-block">
            <h2 style="text-align: left; font-size: 22px;"> Круглосуточная <br> поддержка</h2>
            <p3>+375(29)861-87-65</p3><br>
            <p3>support@gmail.com</p3>
        </div>
    </div>
</body>
</html></title>
</head>
<body>

</body>
</html>

diplom_project/internet_shop/shop/templates/information.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/delivery.css' %}" type="text/css">
    <title>О нас</title>
</head>
<body>
    <div class="first">
        <div class="telephone">
            <div id="tel_logo">
                <img src="{% static 'img/main/smartphone.png' %}" height="25px" width="25px"  alt="photo">
            </div>
            <div id="number">
                <a href="tel:+375(29)396-76-42">+375(29)396-76-42</a>
            </div>
        </div>
        <div id="autorization">
            {%  if request.user.is_authenticated %}
                <p id="class"> {{ user.username }} | <a href="{% url "account:logout" %}">Выйти</a></p>
            {% else %}
                <p id="class"><a href="{% url "account:login" %}">Вход</a> | <a href="{% url "account:register" %}">Регистрация</a></p>
            {% endif %}
        </div>
    </div>
    <!---->
    <div class="content">
        <div class="navigation">
            <div id="mainlogo">
                <img src="{% static "/img/main/modakids-logo.gif" %}" height="150px" width="300px" alt="photo">
            </div>
            <div class="menu">
                <ul class="full-width">
                    <li><a href="{% url 'main' %}">ГЛАВНАЯ</a></li>
                    <li><a href="{% url 'catalog' %}">КАТАЛОГ</a></li>
                    <li><a href="{% url 'delivery' %}">ИНФОРМАЦИЯ</a>
                    <li><a href="{% url 'stock_catalog' %}">АКЦИИ</a></li>
                    <li><a href="{% url 'about' %}">О НАС</a></li>
                </ul>
            </div>
            <div class="container">
                <form action="{% url "cart:cart_detail" %}" style="margin: 10px" id="form-btn">
                    <button id="cart_btn" style="width: 70px; height: 70px;">
                    </button>
                </form>
                <div class="cart">
                    {% with total_items=cart|length %}
                        {% if cart|length > 0 %}
                            <a href="{% url "cart:cart_detail" %}">
                            <div id="sum" style="border: 1px black solid; padding: 5px">
                                {{ total_items }} <br>
                                {{ cart.get_total_price }} руб.
                            </div>
                            </a>
                        {% else %}
                            Корзина пуста
                        {% endif %}
                    {% endwith %}
                </div>
            </div>
        </div>
        <!---->
        <div class="mainview">
            <div id="title">
                <h1>Товары для детей от <span>"0+"</span></h1>
            </div>
            <div id="mainphoto">
                <img src="{% static 'img/main/main photo.jpeg' %}" width="100%" height="100%">
            </div>
        </div>
        <div class='conteiner-info'>
            <div id='menu-block'>
                <ul id="block">
                    <li><a href="{% url 'delivery' %}">ДОСТАВКА</a></li>
                    <li><a href="{%  url 'payment' %}">ОПЛАТА</a></li>
                    <li><a href="{% url 'return' %}">ЗАМЕНА И ВОЗВРАТ ТОВАРА</a></li>
                    <li><a href="{%  url 'contacts' %}">КОНТАКТЫ</a></li>
                </ul>
            </div>
            <div id="info">
            </div>
        </div>
        <!---->
    </div>
        <!---->
    <div class="futer">
        <div id="end-block">
            <h2 style="text-align: left; font-size: 22px;">Следуй за нами:</h2>
            <a href="https://www.instagram.com/evgenij_sidorovich/" target="_blank"><img src="{% static '/img/main/instagram.png' %}" width="40"
            height="40" alt=" Инстаграм"></a>
            <a href="https://vk.com/evgenij_sidorovich" target="_blank"><img src="{% static '/img/main/vk.png' %}" width="40"
            height="40" alt="ВК"></a>
        </div>
        <div id="end-block">
            <h2 style="text-align: left; font-size: 22px;">Время работы</h2>
            <p3>пн-пт: 9:00 - 20:00</p3><br>
            <p3>сб, вс: 9:00 - 19:00</p3><br>
        </div>
        <div id="end-block">
            <h2 style="text-align: left; font-size: 22px;"> Круглосуточная <br> поддержка</h2>
            <p3>+375(29)861-87-65</p3><br>
            <p3>support@gmail.com</p3>
        </div>
    </div>
</body>
</html>